### ISSUE TITLE
Create custom register type

### ISSUE THREAD

**Issue by da1ight** [ITDSystems/alvex-registers#4]
Для создания custom content type использую эту инструкцию:
https://docs.alfresco.com/5.2/tasks/admintools-custom-type-create.html

Перехожу в `Инструменты администратора>Управление моделями>Создать модель`
<img width="582" alt="screen shot 2018-06-20 at 01 37 05" src="https://user-images.githubusercontent.com/15888167/41627798-83f37da0-742a-11e8-9bf4-a1af3f72b395.png">
Далее создаю новый пользовательский тип
<img width="582" alt="screen shot 2018-06-20 at 01 38 59" src="https://user-images.githubusercontent.com/15888167/41627874-ca133262-742a-11e8-8677-01cd130bf190.png">
Перехожу в `Конструктор схемы` и нажимаю `Применить схему по умолчанию`
<img width="738" alt="screen shot 2018-06-20 at 01 41 49" src="https://user-images.githubusercontent.com/15888167/41627990-2d5a119c-742b-11e8-9d5f-ec9dd5d47323.png">
Сохраняюсь и иду дальше на сайт где у меня хранятся реестры документов. Создаю новый реестр и ссылаюсь на только что созданный пользовательский тип.
<img width="526" alt="screen shot 2018-06-20 at 01 44 53" src="https://user-images.githubusercontent.com/15888167/41628078-9658f71c-742b-11e8-9440-794602f2371e.png">
Реестр успешно создается, но при попытке зайти в него выскакивает ошибка:
`Не удалось получить структуру реестра`
<img width="949" alt="screen shot 2018-06-20 at 01 45 04" src="https://user-images.githubusercontent.com/15888167/41628093-ac43d74a-742b-11e8-9304-7a2321370435.png">
Подскажите, что я делаю не так? Возможно я что-то упустил. Уже несколько дней бьюсь с этой задачей.

**Comment by da1ight** [comment]
Так же хотел поинтересоваться, в данный момент модуль находится в статусе 

> In development

Есть ли какие-то сроки выпуска релизной версии?

**Comment by dizaru** [comment]
To **da1ight**: Решилась как-то проблема?

**Comment by da1ight** [comment]
> To **da1ight**: Решилась как-то проблема?

К сожалению нет, забросил. Если удастся раскопать, дайте знать пожалуйста.

**Comment by da1ight** [comment]
Won't fixed
